apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: niginx
    purpose: helm
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: {{ .Values.configmap.port }} #target-port
    nodePort: {{ Values.service.nodePort }}